import Head from "next/head";
import style from "../styles/Home.module.css";
import Header from "@/Components/Header";
import { AiFillInstagram } from "react-icons/ai";
import { BsFacebook, BsWhatsapp } from "react-icons/bs";
import React, { useState, useEffect } from "react";
import NavMenu from "@/Components/NavMenu";
import Aos from "aos";
import "aos/dist/aos.css";
import About from "@/Components/About";
export default function Home() {
  const [open, setOpen] = useState(false);
  useEffect(() => {
    Aos.init({ duration: 2000 });
  }, []);
  return (
    <>
      <Head>
        <title>Ralpha</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/vecon.png" />
      </Head>
      {/* <Link href="/cart">
        <div className={style.cart}>
          <BsCartFill size={25} />
          <span>{cartCount}</span>
        </div>
      </Link>
      <div className={style.container}>
        {products.map((product) => (
          <div className={style.main} key={product.id}>
            <p>{product.clothe}</p>
            <p>{product.size}</p>
            <p>{product.color}</p>
            <Image width={50} height={50} src={product.img} alt="My Image" />
            <button onClick={() => addToCart(product)}>Add To Cart</button>
          </div>
        ))}
      </div> */}
      <div className={style.container} id="#home">
        <div className={style.overlay}>
          <Header isClick={() => setOpen(true)} />
          {open && <NavMenu isClick={() => setOpen(false)} />}
          <div className={style.main}>
            <div className={style.intro} data-aos="fade-up">
              <span>WELCOME TO RALPHA</span>
              <h2>
                Don't just build a brand,
                <br /> Build a Digital Asset.
              </h2>
              <button>START A PROJECT</button>
            </div>
            <div className={style.socials}>
              <BsFacebook size={30} style={{ background: "transparent" }} />
              <BsWhatsapp size={30} style={{ background: "transparent" }} />
              <AiFillInstagram
                size={30}
                style={{ background: "transparent" }}
              />
            </div>
          </div>
        </div>
      </div>
      <About />
    </>
  );
}
